
name: 'logcommit'

on:
  push:
  schedule:
    - cron: '0/30 * * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
          - name: Commit files
            run: |
              git init
              gigit config --local user.email "weixiabing@hotmail.com"
              git config --local user.name "weixiabing"t clone https://github.com/weixiabing/Python-learning.git
              git log -p -1  
