
name: 'logcommit'

on:
  push:
  schedule:
    - cron: '0/30 * * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
     
      - name: Get Git Log
        id: git_log
        uses: JantHsueh/get-git-log-action@master
        with:
          tag: 1.1
      - name: Commit and push if changed   # 更新README.md
        run: |
          git log -p -2
