
name: 'logcommit'

on:
  push:
  schedule:
    - cron: '0/30 * * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
          - name: Commit files
            run: |
              git log -p -1  
