name: 'zhaoolee'

on:
  push:
  schedule:
    - cron: '0 6 * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: gengxin   # 更新README.md
        run: |
         git log -2 > log.txt 
      - name: Build
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config --global user.email "weixiabing@hotmail.com"
          git config --global user.name "weixiabing"
          git add README.md
          git commit -m "Github Action Auto Updated"
          git push
          
