
name: 'logcommit'

on:
  push:
  schedule:
    - cron: '0/30 * * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
          - name: Commit files
            run: |
                 git config --local user.email "weixiabing@hotmail.com"
                 git config --local user.name "weixiabing"
                 git add .
                 git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" #动态提交信息
